kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: sample-web-app
  namespace: default
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - "*"
  gateways:
    - ingress-gateway-configuration
  http:
    - match:
      - uri:  # IF
          prefix: "/experimental"
      - uri:  # OR
          prefix: "/canary"
      route: # THEN
      - destination:
          host: sample-web-app-service
          subset: experimental
    - match:
      - uri :
          prefix: "/"
      route:
      - destination:
          host: sample-web-app-service
          subset: original

# kind: VirtualService
# apiVersion: networking.istio.io/v1alpha3
# metadata:
#   name: sample-web-app
#   namespace: default
# spec:
#   hosts:      # which incoming host are we applying the proxy rules to???
#     - "*"
#   gateways:
#     - ingress-gateway-configuration
#   http:
#     - match:
#       - uri:  # IF
#           prefix: "/experimental"
#       - uri:  # OR
#           prefix: "/canary"
#       route: # THEN
#       - destination:
#           host: sample-web-app-service
#           subset: risky-group
#     - match:
#       - uri :
#           prefix: "/"
#       route:
#       - destination:
#           host: sample-web-app-service
#           subset: safe-group



# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata: 
#   name: sample-web-app # can be any name, no connection with any other name
# spec:
#   hosts:  # the service name that we are applying rule to (incoming host)
#     - "*"
#   gateways:
#     - ingress-gateway-configuration
#   http:
#     - match:
#       - uri:  # IF
#           prefix: "/experimental"
#       route: # THEN
#       - destination:
#           host: sample-web-app-service
#           subset: risky-group
#     - match:
#       - uri :
#           prefix: "/"
#       route:
#       - destination:
#           host: sample-web-app-service
#           subset: safe-group  
#   # http:
#   #   - match:
#   #     - uri: # IF
#   #         prefix: "/experimental"
#   #     route:
#   #     - destination:
#   #         host: sample-web-app-service # target service name, can be any svc
#   #         subset: risky-group
#   #   - route:
#   #     - destination:
#   #         host: sample-web-app-service # target service name, can be any svc
#   #         subset: safe-group





